maybe-picasso/picasso

frontend/src/App.tsx, frontend/src/core/tools/index.ts, frontend/src/core/tools/pen.ts, frontend/src/core/tools/tool.ts, frontend/src/pages/PracticeRoom/components/ColorPicker/index.scss, frontend/src/pages/PracticeRoom/components/ColorPicker/index.tsx, frontend/src/pages/PracticeRoom/components/ToolSizeSelector/index.scss, frontend/src/pages/PracticeRoom/components/ToolSizeSelector/index.tsx, frontend/src/pages/PracticeRoom/index.scss, frontend/src/pages/PracticeRoom/index.tsx, frontend/tsconfig.json
- 진입방법: {picassoURL}/practice-room
- 최상위 클래스인 Tool을 정의
- Tool을 상속받은 Pen 클래스 정의
related to #4 #5
=> feat: 연습방 추가 (개발 테스트용) 및 그림판, 펜 WIP

frontend/src/pages/Room/containers/CanvasContainer.tsx, frontend/src/pages/Room/containers/ChatContainer.tsx, frontend/src/pages/Room/containers/ChatInputContainer.tsx, frontend/src/pages/Room/containers/UserListContainer.tsx, frontend/src/pages/Room/containers/index.tsx, frontend/src/pages/Room/index.scss, frontend/src/pages/Room/index.tsx
좌우 참여자 목록에서 말풍선으로 채팅을 노출할것을 대비하여 배치로 수정하였습니다 귀시코감 :)
=> feat: 룸 레이아웃 배치 변경

frontend/src/pages/Room/components/GameRound/index.tsx, frontend/src/pages/Room/components/GameTimer/index.tsx, frontend/src/pages/Room/components/index.ts, frontend/src/pages/Room/containers/GameHeaderContainer/index.scss, frontend/src/pages/Room/containers/GameHeaderContainer/index.tsx, frontend/src/pages/Room/containers/index.tsx, frontend/src/pages/Room/index.tsx
=> [게임] 타이머, 라운드 UI 배치

frontend/package.json, frontend/src/pages/Room/components/GameRound/index.tsx, frontend/src/pages/Room/components/GameTimer/index.scss, frontend/src/pages/Room/components/GameTimer/index.tsx, frontend/src/pages/Room/containers/GameHeaderContainer/index.scss, frontend/yarn.lock
- date-fns 로 타이머 00:00 포맷으로 설정
- 10초 미만시 강조컬러 설정
- 라운드 정보 스타일링
=> feat: 게임 타이머, 라운드수 UI 스타일 추가

frontend/src/pages/Room/components/ProfileAvatar/index.scss, frontend/src/pages/Room/components/ProfileAvatar/index.tsx, frontend/src/pages/Room/components/index.ts, frontend/src/pages/Room/containers/GameHeaderContainer/index.scss, frontend/src/pages/Room/containers/GateContainer/index.tsx, frontend/src/pages/Room/containers/UserListContainer/index.tsx
Fixes #30
사용자 목록 이미지 프로필 설정값으로 나오도록 처리한 PR입니다. 귀시코감 :)
=> [게임] 사용자 목록 이미지 프로필 설정값으로 나오도록 처리

frontend/src/core/socket.ts, frontend/src/pages/Room/containers/ChatContainer/index.tsx
상대 채팅 메시지 노출 안되는 이슈 수정한 PR입니다 귀시코감~
=> fix: 상대 채팅 메시지 노출 안되는 이슈 수정

frontend/src/core/drawing/drawing-core.ts, frontend/src/core/drawing/drawing.ts, frontend/src/core/socket.ts, frontend/src/pages/PracticeRoom/index.tsx, frontend/src/pages/Room/containers/CanvasContainer/index.tsx, frontend/src/pages/Room/containers/ChatContainer/index.tsx, frontend/src/types/enums.ts, frontend/src/types/global.d.ts
그리기시 상대방 화면에도 그림이 그려지도록 처리한 PR입니다. 귀시코감~
- 그리기 메시지 프로토콜 정의
- 그리기 기능 핸들러 연동
=> [그리기] 소켓 메시지 연동

frontend/src/pages/Room/components/GameQuestion/index.tsx, frontend/src/pages/Room/components/GameRound/index.scss, frontend/src/pages/Room/components/GameRound/index.tsx, frontend/src/pages/Room/components/GameTimer/index.scss, frontend/src/pages/Room/components/index.ts, frontend/src/pages/Room/containers/GameHeaderContainer/index.tsx, frontend/src/pages/Room/containers/GateContainer/index.scss, frontend/src/pages/Room/containers/GateContainer/index.tsx, frontend/src/pages/Room/containers/ToolsContainer/index.tsx
간단한 내용 수정한 PR입니다 귀시코감~
- [chore: 퀴즈 단어 영역 요소 추가](https://github.com/maybe-picasso/picasso/commit/76d1a7bfb99d383270d9aafa132215de823fc128)
- [chore: 프로필 설정시 Input에서 Enter키 입장 가능하도록 Form으로 수정](https://github.com/maybe-picasso/picasso/commit/a0e2242c79c4e43ef888fe6d72251135ade52b63)
- [chore: 그림 전체지우기시 펜 모드로 변경 처리](https://github.com/maybe-picasso/picasso/pull/39/commits/42240296e1215c96508f2ac069bd6dedb2fdbe87)
=> chore: 퀴즈 단어 영역 요소 추가 및 프로필 키 이벤트 수정

frontend/src/pages/Room/containers/CanvasHeaderContainer/index.scss, frontend/src/pages/Room/containers/CanvasHeaderContainer/index.tsx, frontend/src/pages/Room/containers/HeaderContainer/index.scss, frontend/src/pages/Room/containers/HeaderContainer/index.tsx, frontend/src/pages/Room/containers/index.tsx, frontend/src/pages/Room/index.scss, frontend/src/pages/Room/index.tsx
룸 나가기 추가 및 헤더 컨테이너 정리한 PR입니다 귀시코감~
=> feat: 룸 나가기 추가 및 헤더 컨테이너 정리

frontend/src/mocks/store/index.ts, frontend/src/pages/Room/components/GameQuestion/index.tsx, frontend/src/pages/Room/containers/GameContentContainer/index.tsx, frontend/src/pages/Room/containers/GameStatusContainer/index.tsx, frontend/src/pages/Room/containers/ToolsContainer/index.tsx, frontend/src/pages/Room/containers/index.tsx, frontend/src/pages/Room/hooks/index.ts, frontend/src/pages/Room/hooks/useMyTurn.tsx, frontend/src/pages/Room/hooks/usePainterInfo.tsx, frontend/src/pages/Room/index.tsx, frontend/src/stories/2-Room.stories.tsx
문제를 푸는 사람의 화면 상태를 처리한 PR입니다 귀시코감~~
=> feat: 문제 푸는 사람 화면 구성

frontend/src/mocks/store/index.ts, frontend/src/pages/Room/components/ProfileAvatar/index.scss, frontend/src/pages/Room/components/ProfileAvatar/index.tsx, frontend/src/pages/Room/components/overlay/CompleteContent/index.scss, frontend/src/pages/Room/components/overlay/CompleteContent/index.tsx, frontend/src/pages/Room/containers/ChatContainer/index.scss, frontend/src/pages/Room/containers/UserListContainer/index.scss, frontend/src/pages/Room/containers/UserListContainer/index.tsx
- 라운드 완료시 UI 
- 현재 턴 표시 사이즈 조정, 모션 추가
=> feat: 라운드 완료시 UI, 현재턴 표시 모션 추가

frontend/package.json, frontend/yarn.lock
- 스토리북을 6.5.6 버전으로 업데이트한 PR입니다 귀시코감~~
=> chore: 스토리북 버전 6.5.6 업데이트

frontend/src/core/drawing/drawing.ts, frontend/src/types/enums.ts
=> feat: undo / redo 기능 추가

frontend/src/constants/index.ts, frontend/src/helpers/storage.ts, frontend/src/pages/Room/containers/GateContainer/index.tsx
=> feat: 로컬스토리지 헬퍼 추가

frontend/src/pages/Room/components/PaletteSlider/index.tsx, frontend/src/pages/Room/containers/ToolsContainer/index.tsx, frontend/src/store/models/tools.ts
- 마지막 선택한 도구 상태를 localStorage에 저장했다가, 새로고침시 불러오기 기능 추가.
=> feat: 도구 상태 restore 기능 추가

frontend/src/pages/Room/containers/DevLogContainer/index.scss, frontend/src/pages/Room/containers/DevLogContainer/index.tsx, frontend/src/pages/Room/containers/index.tsx, frontend/src/pages/Room/index.tsx, frontend/src/store/models/game.ts
개발모드에서 필요한 정보를 하단에 노출한 PR입니다 귀시코감~
=> feat: 개발 상태값 로그 추가

frontend/src/core/drawing/drawing-core.ts, frontend/src/core/drawing/drawing.ts, frontend/src/pages/Room/containers/CanvasContainer/index.tsx, frontend/src/types/global.d.ts
사용자간 캔버스 사이즈 차이 좌표 보정한 PR입니다 귀시코감~~ 
- [feat: 출제자와 캔버스 사이즈 차이로 인한 좌표 보정 처리](https://github.com/maybe-picasso/picasso/pull/77/commits/41dbc99c7fcc3f1b836c25ee2d5fae319645a631)
- [chore: 그리기 차례가되면 사용하던 그리기 설정으로 적용](https://github.com/maybe-picasso/picasso/pull/77/commits/ef705ce4f2349d7fd0f7e5d2a52ae42aa27e9acd)
=> feat: 출제자와 캔버스 사이즈 차이로 인한 좌표 보정 처리

backend/src/app.socket.ts, frontend/src/pages/Room/containers/HeaderContainer/index.tsx, frontend/src/pages/Room/hooks/index.ts, frontend/src/pages/Room/hooks/useGameHandler.tsx, frontend/src/pages/Room/hooks/useGameSync.tsx, frontend/src/pages/Room/index.tsx, frontend/src/types/enums.ts
Fixes #80
- 게임 진행중에 입장한 유저 진행 상태 싱크 처리한 PR입니다 귀시코감~
=> [게임] 진행중 입장한 유저 진행 상태 싱크 처리

frontend/src/mocks/store/index.ts, frontend/src/pages/Room/containers/UserListContainer/index.tsx, frontend/src/stories/2-Room.stories.tsx
=> feat: 유저 목록 응답 로딩중 스켈레톤 추가

frontend/src/pages/Room/hooks/useGameHandler.tsx
전원 조기 정답시 다음 스테이지로 이동처리한 PR입니다~
=> feat: 전원 조기 정답시 처리 Fixes #86

frontend/src/pages/Room/containers/ChatContainer/index.scss, frontend/src/pages/Room/containers/ChatContainer/index.tsx
- 최하단이 아닐경우 최신 대화로 이동하는 버튼 추가
- 메시지 전송시 최하단 스크롤 이동, ref가 잘못 적용되어 있던 부분 수정
=> fix: 채팅창 최신 메시지 스크롤  버튼 추가

README.md, frontend/src/mocks/store/index.ts, frontend/src/pages/Room/containers/ChatContainer/index.scss, frontend/src/pages/Room/containers/ChatContainer/index.tsx, frontend/src/pages/Room/containers/UserListContainer/index.tsx, frontend/src/pages/Room/hooks/useGameHandler.tsx, frontend/src/stories/2-Room.stories.tsx
- feat: 유저 목록 응답 로딩중 스켈레톤 추가
- feat: 전원 조기 정답시 처리
- feat: 채팅창 최신 메시지 스크롤 버튼 추가
=> deploy: Merge to master

frontend/package.json, frontend/src/mocks/store/gamePoint.ts, frontend/src/mocks/store/index.ts, frontend/src/pages/Room/components/GameQuestion/index.tsx, frontend/src/pages/Room/containers/GameContentContainer/index.tsx, frontend/src/pages/Room/hooks/index.ts, frontend/src/pages/Room/hooks/useMyCorrect.tsx, frontend/yarn.lock
정답을 맞출시 정답 단어와 축하 이모지가 노출됩니다.
- [feat: 정답자 에니메이션 추가](https://github.com/maybe-picasso/picasso/commit/76f3b84beb43ae07e37c7798f27068e804123428)
- [chore: 상단 문제 단어 노출 영역 스타일 수정](https://github.com/maybe-picasso/picasso/commit/c83d7f43b18a2ac4512c3b0b2fe78ad5693a2c7d)
=> feat: 정답자 에니메이션 추가

frontend/src/pages/Room/components/overlay/NextTurnContent/index.tsx, frontend/src/pages/Room/containers/GameContentContainer/index.tsx, frontend/src/pages/Room/hooks/usePainterInfo.tsx
닉네임 옆에 프로필 이모지 함께 노출되도록 수정한 PR입니다~
=> feat: 다음턴 플레이어 프로필 이모지 노출 추가

frontend/src/core/drawing/drawing.ts
=> fix: 그리기 클리어시 큐배열 리셋

frontend/src/mocks/store/index.ts, frontend/src/pages/Room/components/GameRound/index.tsx, frontend/src/pages/Room/components/GameTimer/index.tsx, frontend/src/pages/Room/components/index.ts, frontend/src/pages/Room/components/overlay/ReadyContent/index.scss, frontend/src/pages/Room/components/overlay/ReadyContent/index.tsx, frontend/src/pages/Room/components/overlay/ResultLayer/index.scss, frontend/src/pages/Room/components/overlay/ResultLayer/index.tsx, frontend/src/pages/Room/containers/CanvasContainer/index.tsx, frontend/src/pages/Room/containers/DevLogContainer/index.tsx, frontend/src/pages/Room/containers/GameContentContainer/index.tsx, frontend/src/pages/Room/hooks/index.ts, frontend/src/pages/Room/hooks/useFirstUser.tsx, frontend/src/pages/Room/hooks/useGameHandler.tsx, frontend/src/pages/Room/hooks/useGameStatus.tsx, frontend/src/pages/Room/hooks/useGameSync.tsx, frontend/src/pages/Room/index.tsx, frontend/src/store/models/game.ts, frontend/src/stories/2-Room.stories.tsx, frontend/src/types/enums.ts
기존 두명이상 접속시 바로 게임이 시작되어 다른 사람을 기다릴 수 없는 상황으로
참석자들의 준비 후 게임이 시작되도록 참여자 준비 현황을 보여주는 화면을 추가하였습니다~ 귀시코감 :)
- [feat: 참여자 준비 현황 화면 추가](https://github.com/maybe-picasso/picasso/commit/7fb6cd139d5a13757acef4d9d0accb46a72d6516)
- [feat: 참여자 준비 현황 상태 소켓 핸들링](https://github.com/maybe-picasso/picasso/commit/865cb60da122547245ef0fe9e07c2d13f2d69e53)
- [chore: 플레이어 대기 상태 변수 수정](https://github.com/maybe-picasso/picasso/commit/696f399407ef8e3950a193a25d000fc290d9fdc3)
=> feat: 참여자 준비 현황 화면 추가

frontend/src/pages/Room/components/PaletteSlider/index.tsx, frontend/src/pages/Room/containers/ToolsContainer/index.scss, frontend/src/pages/Room/containers/ToolsContainer/index.tsx
=> feat: 브러시 사이즈 프리뷰 추가

frontend/src/store/models/gamePoint.ts, frontend/src/store/models/room.ts
=> fix: 점수 누락되는 부분 수정 Fixes #88

frontend/package.json, frontend/src/App.tsx, frontend/src/components/ErrorBoundary/index.scss, frontend/src/components/ErrorBoundary/index.tsx, frontend/yarn.lock
=> feat: ErrorBoundary 추가

frontend/src/mocks/store/chat.ts, frontend/src/pages/Room/containers/ChatContainer/index.scss, frontend/src/pages/Room/containers/ChatContainer/index.tsx, frontend/src/pages/Room/hooks/useGameHandler.tsx, frontend/src/store/models/chat.ts, frontend/src/store/models/game.ts
=> feat: 그리기중인 페인터 나갔을때 처리
